// This file is generated by Stringer. Do not edit manually.
import { defineRouting } from "next-intl/routing";

export const routing = defineRouting({
  // A list of all locales that are supported
  locales: ["en", "es"],

  // Used when no locale matches
  defaultLocale: "en",

  // The `pathnames` object holds pairs of internal and
  // external pathnames. Based on the locale, the external
  // pathname is rewritten to the shared, internal one.
  pathnames: {
    // If all locales use the same pathname, a single
    // external pathname can be provided for all locales
    "/": "/",
    "/about": "/about",
  },
});
