/**
 * Database Type Definitions
 * Generated from: supabase/migrations/1764175000_complete_database_schema.sql
 * Total Tables: 25
 * Last Updated: 2025-11-26
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          phone: string | null;
          provider_sub: string | null;
          user_id: string | null;
          created_at: string;
          updated_at: string;
          last_login: string | null;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          provider_sub?: string | null;
          user_id?: string | null;
          created_at?: string;
          updated_at?: string;
          last_login?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          provider_sub?: string | null;
          user_id?: string | null;
          created_at?: string;
          updated_at?: string;
          last_login?: string | null;
        };
      };
      gmb_accounts: {
        Row: {
          id: string;
          user_id: string | null;
          account_id: string | null;
          account_name: string | null;
          email: string | null;
          google_account_id: string | null;
          access_token: string | null;
          refresh_token: string | null;
          token_expires_at: string | null;
          is_active: boolean | null;
          last_sync: string | null;
          data_retention_days: number | null;
          delete_on_disconnect: boolean | null;
          disconnected_at: string | null;
          settings: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          account_id?: string | null;
          account_name?: string | null;
          email?: string | null;
          google_account_id?: string | null;
          access_token?: string | null;
          refresh_token?: string | null;
          token_expires_at?: string | null;
          is_active?: boolean | null;
          last_sync?: string | null;
          data_retention_days?: number | null;
          delete_on_disconnect?: boolean | null;
          disconnected_at?: string | null;
          settings?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          account_id?: string | null;
          account_name?: string | null;
          email?: string | null;
          google_account_id?: string | null;
          access_token?: string | null;
          refresh_token?: string | null;
          token_expires_at?: string | null;
          is_active?: boolean | null;
          last_sync?: string | null;
          data_retention_days?: number | null;
          delete_on_disconnect?: boolean | null;
          disconnected_at?: string | null;
          settings?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      gmb_locations: {
        Row: {
          id: string;
          gmb_account_id: string;
          user_id: string | null;
          location_id: string;
          normalized_location_id: string | null;
          location_name: string | null;
          account_id: string | null;
          address: string | null;
          phone: string | null;
          website: string | null;
          category: string | null;
          additional_categories: string[] | null;
          description: string | null;
          short_description: string | null;
          latitude: number | null;
          longitude: number | null;
          latlng: string | null;
          rating: number | null;
          review_count: number | null;
          business_hours: Json | null;
          regularhours: Json | null;
          opening_date: string | null;
          cover_photo_url: string | null;
          profile_completeness: number | null;
          health_score: number | null;
          response_rate: number | null;
          calculated_response_rate: number | null;
          service_area_enabled: boolean | null;
          from_the_business: string[] | null;
          metadata: Json | null;
          ai_insights: string | null;
          status: string | null;
          type: string | null;
          is_active: boolean | null;
          is_archived: boolean | null;
          is_syncing: boolean | null;
          archived_at: string | null;
          last_synced_at: string | null;
          location_id_external: string | null;
          appointment_url: string | null;
          booking_url: string | null;
          menu_url: string | null;
          order_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          gmb_account_id: string;
          user_id?: string | null;
          location_id: string;
          normalized_location_id?: string | null;
          location_name?: string | null;
          account_id?: string | null;
          address?: string | null;
          phone?: string | null;
          website?: string | null;
          category?: string | null;
          additional_categories?: string[] | null;
          description?: string | null;
          short_description?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          latlng?: string | null;
          rating?: number | null;
          review_count?: number | null;
          business_hours?: Json | null;
          regularhours?: Json | null;
          opening_date?: string | null;
          cover_photo_url?: string | null;
          profile_completeness?: number | null;
          health_score?: number | null;
          response_rate?: number | null;
          calculated_response_rate?: number | null;
          service_area_enabled?: boolean | null;
          from_the_business?: string[] | null;
          metadata?: Json | null;
          ai_insights?: string | null;
          status?: string | null;
          type?: string | null;
          is_active?: boolean | null;
          is_archived?: boolean | null;
          is_syncing?: boolean | null;
          archived_at?: string | null;
          last_synced_at?: string | null;
          location_id_external?: string | null;
          appointment_url?: string | null;
          booking_url?: string | null;
          menu_url?: string | null;
          order_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          gmb_account_id?: string;
          user_id?: string | null;
          location_id?: string;
          normalized_location_id?: string | null;
          location_name?: string | null;
          account_id?: string | null;
          address?: string | null;
          phone?: string | null;
          website?: string | null;
          category?: string | null;
          additional_categories?: string[] | null;
          description?: string | null;
          short_description?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          latlng?: string | null;
          rating?: number | null;
          review_count?: number | null;
          business_hours?: Json | null;
          regularhours?: Json | null;
          opening_date?: string | null;
          cover_photo_url?: string | null;
          profile_completeness?: number | null;
          health_score?: number | null;
          response_rate?: number | null;
          calculated_response_rate?: number | null;
          service_area_enabled?: boolean | null;
          from_the_business?: string[] | null;
          metadata?: Json | null;
          ai_insights?: string | null;
          status?: string | null;
          type?: string | null;
          is_active?: boolean | null;
          is_archived?: boolean | null;
          is_syncing?: boolean | null;
          archived_at?: string | null;
          last_synced_at?: string | null;
          location_id_external?: string | null;
          appointment_url?: string | null;
          booking_url?: string | null;
          menu_url?: string | null;
          order_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      gmb_reviews: {
        Row: {
          id: string;
          location_id: string;
          user_id: string | null;
          gmb_account_id: string | null;
          account_id: string | null;
          external_review_id: string | null;
          review_id: string | null;
          reviewer_name: string | null;
          reviewer_display_name: string | null;
          reviewer_profile_photo_url: string | null;
          rating: number;
          review_text: string | null;
          comment: string | null;
          review_date: string | null;
          review_timestamp: string | null;
          reply_text: string | null;
          reply_date: string | null;
          reply_timestamp: string | null;
          response: string | null;
          response_text: string | null;
          has_reply: boolean | null;
          has_response: boolean | null;
          replied_at: string | null;
          responded_at: string | null;
          review_reply: string | null;
          review_url: string | null;
          google_my_business_name: string | null;
          ai_suggested_reply: string | null;
          ai_generated_response: string | null;
          ai_reply_generated: boolean | null;
          ai_confidence_score: number | null;
          ai_sentiment: string | null;
          ai_sentiment_score: number | null;
          ai_sentiment_analysis: Json | null;
          ai_generated_at: string | null;
          ai_sent_at: string | null;
          auto_reply_enabled: boolean | null;
          auto_reply_status: string | null;
          response_priority: string | null;
          status: string | null;
          tags: string[] | null;
          is_verified_purchase: boolean | null;
          is_anonymized: boolean | null;
          is_archived: boolean | null;
          archived_at: string | null;
          flagged_reason: string | null;
          internal_notes: string | null;
          metadata: Json | null;
          synced_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          location_id: string;
          user_id?: string | null;
          gmb_account_id?: string | null;
          account_id?: string | null;
          external_review_id?: string | null;
          review_id?: string | null;
          reviewer_name?: string | null;
          reviewer_display_name?: string | null;
          reviewer_profile_photo_url?: string | null;
          rating: number;
          review_text?: string | null;
          comment?: string | null;
          review_date?: string | null;
          review_timestamp?: string | null;
          reply_text?: string | null;
          reply_date?: string | null;
          reply_timestamp?: string | null;
          response?: string | null;
          response_text?: string | null;
          has_reply?: boolean | null;
          has_response?: boolean | null;
          replied_at?: string | null;
          responded_at?: string | null;
          review_reply?: string | null;
          review_url?: string | null;
          google_my_business_name?: string | null;
          ai_suggested_reply?: string | null;
          ai_generated_response?: string | null;
          ai_reply_generated?: boolean | null;
          ai_confidence_score?: number | null;
          ai_sentiment?: string | null;
          ai_sentiment_score?: number | null;
          ai_sentiment_analysis?: Json | null;
          ai_generated_at?: string | null;
          ai_sent_at?: string | null;
          auto_reply_enabled?: boolean | null;
          auto_reply_status?: string | null;
          response_priority?: string | null;
          status?: string | null;
          tags?: string[] | null;
          is_verified_purchase?: boolean | null;
          is_anonymized?: boolean | null;
          is_archived?: boolean | null;
          archived_at?: string | null;
          flagged_reason?: string | null;
          internal_notes?: string | null;
          metadata?: Json | null;
          synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          location_id?: string;
          user_id?: string | null;
          gmb_account_id?: string | null;
          account_id?: string | null;
          external_review_id?: string | null;
          review_id?: string | null;
          reviewer_name?: string | null;
          reviewer_display_name?: string | null;
          reviewer_profile_photo_url?: string | null;
          rating?: number;
          review_text?: string | null;
          comment?: string | null;
          review_date?: string | null;
          review_timestamp?: string | null;
          reply_text?: string | null;
          reply_date?: string | null;
          reply_timestamp?: string | null;
          response?: string | null;
          response_text?: string | null;
          has_reply?: boolean | null;
          has_response?: boolean | null;
          replied_at?: string | null;
          responded_at?: string | null;
          review_reply?: string | null;
          review_url?: string | null;
          google_my_business_name?: string | null;
          ai_suggested_reply?: string | null;
          ai_generated_response?: string | null;
          ai_reply_generated?: boolean | null;
          ai_confidence_score?: number | null;
          ai_sentiment?: string | null;
          ai_sentiment_score?: number | null;
          ai_sentiment_analysis?: Json | null;
          ai_generated_at?: string | null;
          ai_sent_at?: string | null;
          auto_reply_enabled?: boolean | null;
          auto_reply_status?: string | null;
          response_priority?: string | null;
          status?: string | null;
          tags?: string[] | null;
          is_verified_purchase?: boolean | null;
          is_anonymized?: boolean | null;
          is_archived?: boolean | null;
          archived_at?: string | null;
          flagged_reason?: string | null;
          internal_notes?: string | null;
          metadata?: Json | null;
          synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      gmb_questions: {
        Row: {
          id: string;
          location_id: string;
          user_id: string;
          gmb_account_id: string;
          question_id: string | null;
          external_question_id: string | null;
          google_resource_name: string | null;
          question_text: string;
          question_url: string | null;
          author_name: string | null;
          author_display_name: string | null;
          author_profile_photo_url: string | null;
          author_type: string | null;
          asked_at: string | null;
          answer_id: string | null;
          answer_text: string | null;
          answer_status: string | null;
          answered_at: string | null;
          answered_by: string | null;
          upvote_count: number | null;
          total_answer_count: number | null;
          language_code: string | null;
          ai_suggested_answer: string | null;
          ai_answer_generated: boolean | null;
          ai_confidence_score: number | null;
          ai_category: string | null;
          status: string | null;
          priority: string | null;
          is_featured: boolean | null;
          is_hidden: boolean | null;
          is_archived: boolean | null;
          archived_at: string | null;
          internal_notes: string | null;
          metadata: Json | null;
          synced_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          location_id: string;
          user_id: string;
          gmb_account_id: string;
          question_id?: string | null;
          external_question_id?: string | null;
          google_resource_name?: string | null;
          question_text: string;
          question_url?: string | null;
          author_name?: string | null;
          author_display_name?: string | null;
          author_profile_photo_url?: string | null;
          author_type?: string | null;
          asked_at?: string | null;
          answer_id?: string | null;
          answer_text?: string | null;
          answer_status?: string | null;
          answered_at?: string | null;
          answered_by?: string | null;
          upvote_count?: number | null;
          total_answer_count?: number | null;
          language_code?: string | null;
          ai_suggested_answer?: string | null;
          ai_answer_generated?: boolean | null;
          ai_confidence_score?: number | null;
          ai_category?: string | null;
          status?: string | null;
          priority?: string | null;
          is_featured?: boolean | null;
          is_hidden?: boolean | null;
          is_archived?: boolean | null;
          archived_at?: string | null;
          internal_notes?: string | null;
          metadata?: Json | null;
          synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          location_id?: string;
          user_id?: string;
          gmb_account_id?: string;
          question_id?: string | null;
          external_question_id?: string | null;
          google_resource_name?: string | null;
          question_text?: string;
          question_url?: string | null;
          author_name?: string | null;
          author_display_name?: string | null;
          author_profile_photo_url?: string | null;
          author_type?: string | null;
          asked_at?: string | null;
          answer_id?: string | null;
          answer_text?: string | null;
          answer_status?: string | null;
          answered_at?: string | null;
          answered_by?: string | null;
          upvote_count?: number | null;
          total_answer_count?: number | null;
          language_code?: string | null;
          ai_suggested_answer?: string | null;
          ai_answer_generated?: boolean | null;
          ai_confidence_score?: number | null;
          ai_category?: string | null;
          status?: string | null;
          priority?: string | null;
          is_featured?: boolean | null;
          is_hidden?: boolean | null;
          is_archived?: boolean | null;
          archived_at?: string | null;
          internal_notes?: string | null;
          metadata?: Json | null;
          synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      gmb_posts: {
        Row: {
          id: string;
          location_id: string;
          user_id: string;
          post_id: string | null;
          provider_post_id: string | null;
          title: string | null;
          content: string;
          post_type: string | null;
          media_url: string | null;
          call_to_action: string | null;
          call_to_action_url: string | null;
          cta_type: string | null;
          cta_url: string | null;
          start_date: string | null;
          end_date: string | null;
          status: string | null;
          published_at: string | null;
          scheduled_at: string | null;
          is_archived: boolean | null;
          archived_at: string | null;
          error_message: string | null;
          metadata: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          location_id: string;
          user_id: string;
          post_id?: string | null;
          provider_post_id?: string | null;
          title?: string | null;
          content: string;
          post_type?: string | null;
          media_url?: string | null;
          call_to_action?: string | null;
          call_to_action_url?: string | null;
          cta_type?: string | null;
          cta_url?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          status?: string | null;
          published_at?: string | null;
          scheduled_at?: string | null;
          is_archived?: boolean | null;
          archived_at?: string | null;
          error_message?: string | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          location_id?: string;
          user_id?: string;
          post_id?: string | null;
          provider_post_id?: string | null;
          title?: string | null;
          content?: string;
          post_type?: string | null;
          media_url?: string | null;
          call_to_action?: string | null;
          call_to_action_url?: string | null;
          cta_type?: string | null;
          cta_url?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          status?: string | null;
          published_at?: string | null;
          scheduled_at?: string | null;
          is_archived?: boolean | null;
          archived_at?: string | null;
          error_message?: string | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      gmb_media: {
        Row: {
          id: string;
          location_id: string;
          user_id: string;
          gmb_account_id: string;
          external_media_id: string;
          url: string | null;
          thumbnail_url: string | null;
          type: string | null;
          metadata: Json | null;
          synced_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          location_id: string;
          user_id: string;
          gmb_account_id: string;
          external_media_id: string;
          url?: string | null;
          thumbnail_url?: string | null;
          type?: string | null;
          metadata?: Json | null;
          synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          location_id?: string;
          user_id?: string;
          gmb_account_id?: string;
          external_media_id?: string;
          url?: string | null;
          thumbnail_url?: string | null;
          type?: string | null;
          metadata?: Json | null;
          synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      gmb_performance_metrics: {
        Row: {
          id: string;
          location_id: string;
          user_id: string;
          gmb_account_id: string;
          metric_date: string;
          metric_type: string;
          metric_value: number | null;
          sub_entity_type: Json | null;
          metadata: Json | null;
          synced_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          location_id: string;
          user_id: string;
          gmb_account_id: string;
          metric_date: string;
          metric_type: string;
          metric_value?: number | null;
          sub_entity_type?: Json | null;
          metadata?: Json | null;
          synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          location_id?: string;
          user_id?: string;
          gmb_account_id?: string;
          metric_date?: string;
          metric_type?: string;
          metric_value?: number | null;
          sub_entity_type?: Json | null;
          metadata?: Json | null;
          synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      gmb_search_keywords: {
        Row: {
          id: string;
          location_id: string;
          user_id: string;
          gmb_account_id: string;
          month_year: string;
          search_keyword: string;
          impressions_count: number | null;
          threshold_value: number | null;
          metadata: Json | null;
          synced_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          location_id: string;
          user_id: string;
          gmb_account_id: string;
          month_year: string;
          search_keyword: string;
          impressions_count?: number | null;
          threshold_value?: number | null;
          metadata?: Json | null;
          synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          location_id?: string;
          user_id?: string;
          gmb_account_id?: string;
          month_year?: string;
          search_keyword?: string;
          impressions_count?: number | null;
          threshold_value?: number | null;
          metadata?: Json | null;
          synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      gmb_metrics: {
        Row: {
          id: string;
          user_id: string;
          gmb_account_id: string;
          phase: string;
          runs_count: number | null;
          total_duration_ms: number | null;
          avg_duration_ms: number | null;
          total_items_count: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          gmb_account_id: string;
          phase: string;
          runs_count?: number | null;
          total_duration_ms?: number | null;
          avg_duration_ms?: number | null;
          total_items_count?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          gmb_account_id?: string;
          phase?: string;
          runs_count?: number | null;
          total_duration_ms?: number | null;
          avg_duration_ms?: number | null;
          total_items_count?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      ai_requests: {
        Row: {
          id: string;
          user_id: string;
          location_id: string | null;
          provider: string;
          model: string;
          feature: string;
          prompt_tokens: number | null;
          completion_tokens: number | null;
          total_tokens: number | null;
          cost_usd: number | null;
          latency_ms: number | null;
          success: boolean | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          location_id?: string | null;
          provider: string;
          model: string;
          feature: string;
          prompt_tokens?: number | null;
          completion_tokens?: number | null;
          total_tokens?: number | null;
          cost_usd?: number | null;
          latency_ms?: number | null;
          success?: boolean | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          location_id?: string | null;
          provider?: string;
          model?: string;
          feature?: string;
          prompt_tokens?: number | null;
          completion_tokens?: number | null;
          total_tokens?: number | null;
          cost_usd?: number | null;
          latency_ms?: number | null;
          success?: boolean | null;
          created_at?: string;
        };
      };
      ai_settings: {
        Row: {
          id: string;
          user_id: string;
          provider: string;
          api_key: string;
          priority: number | null;
          is_active: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          provider: string;
          api_key: string;
          priority?: number | null;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          provider?: string;
          api_key?: string;
          priority?: number | null;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      sync_queue: {
        Row: {
          id: string;
          user_id: string;
          gmb_account_id: string;
          job_type: string;
          priority: number | null;
          status: string | null;
          retry_count: number | null;
          max_retries: number | null;
          error_message: string | null;
          metadata: Json | null;
          scheduled_at: string | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          gmb_account_id: string;
          job_type: string;
          priority?: number | null;
          status?: string | null;
          retry_count?: number | null;
          max_retries?: number | null;
          error_message?: string | null;
          metadata?: Json | null;
          scheduled_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          gmb_account_id?: string;
          job_type?: string;
          priority?: number | null;
          status?: string | null;
          retry_count?: number | null;
          max_retries?: number | null;
          error_message?: string | null;
          metadata?: Json | null;
          scheduled_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
      };
      sync_status: {
        Row: {
          id: string;
          user_id: string;
          gmb_account_id: string;
          last_sync_at: string | null;
          next_sync_at: string | null;
          sync_frequency: string | null;
          is_syncing: boolean | null;
          last_error: string | null;
          consecutive_failures: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          gmb_account_id: string;
          last_sync_at?: string | null;
          next_sync_at?: string | null;
          sync_frequency?: string | null;
          is_syncing?: boolean | null;
          last_error?: string | null;
          consecutive_failures?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          gmb_account_id?: string;
          last_sync_at?: string | null;
          next_sync_at?: string | null;
          sync_frequency?: string | null;
          is_syncing?: boolean | null;
          last_error?: string | null;
          consecutive_failures?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      gmb_sync_logs: {
        Row: {
          id: string;
          user_id: string;
          gmb_account_id: string;
          phase: string;
          status: string;
          started_at: string | null;
          ended_at: string | null;
          duration_ms: number | null;
          counts: Json | null;
          error: string | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          gmb_account_id: string;
          phase: string;
          status: string;
          started_at?: string | null;
          ended_at?: string | null;
          duration_ms?: number | null;
          counts?: Json | null;
          error?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          gmb_account_id?: string;
          phase?: string;
          status?: string;
          started_at?: string | null;
          ended_at?: string | null;
          duration_ms?: number | null;
          counts?: Json | null;
          error?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
      };
      oauth_states: {
        Row: {
          id: string;
          user_id: string | null;
          state: string;
          expires_at: string;
          used: boolean | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          state: string;
          expires_at: string;
          used?: boolean | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          state?: string;
          expires_at?: string;
          used?: boolean | null;
          created_at?: string;
        };
      };
      oauth_tokens: {
        Row: {
          id: string;
          user_id: string;
          provider: string;
          access_token: string | null;
          refresh_token: string | null;
          expires_at: string | null;
          scope: string | null;
          metadata: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          provider: string;
          access_token?: string | null;
          refresh_token?: string | null;
          expires_at?: string | null;
          scope?: string | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          provider?: string;
          access_token?: string | null;
          refresh_token?: string | null;
          expires_at?: string | null;
          scope?: string | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      performance_metrics: {
        Row: {
          id: string;
          user_id: string | null;
          name: string;
          value: number;
          unit: string;
          metadata: Json | null;
          timestamp: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          name: string;
          value: number;
          unit: string;
          metadata?: Json | null;
          timestamp?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          name?: string;
          value?: number;
          unit?: string;
          metadata?: Json | null;
          timestamp?: string | null;
        };
      };
      rate_limit_requests: {
        Row: {
          id: string;
          user_id: string;
          action: string;
          endpoint: string | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          action: string;
          endpoint?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          action?: string;
          endpoint?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
      activity_logs: {
        Row: {
          id: string;
          user_id: string | null;
          activity_type: string;
          activity_message: string;
          actionable: boolean | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          activity_type: string;
          activity_message: string;
          actionable?: boolean | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          activity_type?: string;
          activity_message?: string;
          actionable?: boolean | null;
          metadata?: Json | null;
          created_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          user_id: string | null;
          action: string;
          resource_type: string | null;
          resource_id: string | null;
          ip_address: string | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          action: string;
          resource_type?: string | null;
          resource_id?: string | null;
          ip_address?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          action?: string;
          resource_type?: string | null;
          resource_id?: string | null;
          ip_address?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
      };
      error_logs: {
        Row: {
          id: string;
          user_id: string | null;
          message: string;
          error_type: string | null;
          error_code: string | null;
          stack: string | null;
          level: string | null;
          severity: number | null;
          url: string | null;
          user_agent: string | null;
          ip_address: string | null;
          browser_name: string | null;
          browser_version: string | null;
          os_name: string | null;
          os_version: string | null;
          device_type: string | null;
          session_id: string | null;
          context: Json | null;
          resolved: boolean | null;
          resolved_by: string | null;
          resolved_at: string | null;
          resolution_notes: string | null;
          timestamp: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          message: string;
          error_type?: string | null;
          error_code?: string | null;
          stack?: string | null;
          level?: string | null;
          severity?: number | null;
          url?: string | null;
          user_agent?: string | null;
          ip_address?: string | null;
          browser_name?: string | null;
          browser_version?: string | null;
          os_name?: string | null;
          os_version?: string | null;
          device_type?: string | null;
          session_id?: string | null;
          context?: Json | null;
          resolved?: boolean | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          resolution_notes?: string | null;
          timestamp?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          message?: string;
          error_type?: string | null;
          error_code?: string | null;
          stack?: string | null;
          level?: string | null;
          severity?: number | null;
          url?: string | null;
          user_agent?: string | null;
          ip_address?: string | null;
          browser_name?: string | null;
          browser_version?: string | null;
          os_name?: string | null;
          os_version?: string | null;
          device_type?: string | null;
          session_id?: string | null;
          context?: Json | null;
          resolved?: boolean | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          resolution_notes?: string | null;
          timestamp?: string | null;
          created_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          message: string;
          link: string | null;
          read: boolean | null;
          metadata: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          message: string;
          link?: string | null;
          read?: boolean | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          title?: string;
          message?: string;
          link?: string | null;
          read?: boolean | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      weekly_task_recommendations: {
        Row: {
          id: string;
          user_id: string;
          week_start_date: string;
          week_end_date: string;
          title: string;
          description: string | null;
          category: string | null;
          priority: string | null;
          effort_level: string | null;
          estimated_minutes: number | null;
          expected_impact: string | null;
          reasoning: string | null;
          insights: string | null;
          tasks: Json | null;
          status: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          week_start_date: string;
          week_end_date: string;
          title: string;
          description?: string | null;
          category?: string | null;
          priority?: string | null;
          effort_level?: string | null;
          estimated_minutes?: number | null;
          expected_impact?: string | null;
          reasoning?: string | null;
          insights?: string | null;
          tasks?: Json | null;
          status?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          week_start_date?: string;
          week_end_date?: string;
          title?: string;
          description?: string | null;
          category?: string | null;
          priority?: string | null;
          effort_level?: string | null;
          estimated_minutes?: number | null;
          expected_impact?: string | null;
          reasoning?: string | null;
          insights?: string | null;
          tasks?: Json | null;
          status?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      business_profile_history: {
        Row: {
          id: string;
          location_id: string;
          location_name: string;
          operation_type: string;
          data: Json;
          metadata: Json | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          location_id: string;
          location_name: string;
          operation_type: string;
          data: Json;
          metadata?: Json | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          location_id?: string;
          location_name?: string;
          operation_type?: string;
          data?: Json;
          metadata?: Json | null;
          created_by?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      cleanup_rate_limit_requests: {
        Args: Record<PropertyKey, never>;
        Returns: void;
      };
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
